title: Making 3D fault geometries from cross-sections
description: This tutorial describes how to create complex 3d fault geometries from geologic map and cross-section data using QGIS, with some plugins created for this purpose.
theme: just-the-docs
baseurl: /fault-geometry-building-tutorial
# Optional: enable Just the Docs features
just_the_docs:
  search_enabled: true
  heading_anchors: true