title: CRESCENT QGIS Plugins Tutorial
description: This tutorial describes how to create complex 3d fault geometries from geologic map and cross-section data using QGIS, with some plugins created for this purpose.
theme: jekyll-theme-slate
markdown: kramdown
